#!/bin/bash
#-------------------------------------------------------------------------------
# loco | loco user interface
#-------------------------------------------------------------------------------

set -eu

# launch the main.sh script and the finish.sh one 
# needed to execute main.sh as root, finish.sh as $USER and close terminal
./src/main.sh "${@-}" && ./src/temp/finish.sh && kill -9 $PPID 2&>/dev/null