#!/bin/bash
#-------------------------------------------------------------------------------
# clean_profiles.sh | clean the loco profiles before release
#-------------------------------------------------------------------------------

set -eu

#######################################
# Remove files from profiles folders
#######################################
clean_profiles(){
	# remove vim bundles from dist
	sudo rm -fr profiles/*/dotfiles/.vim/bundle/*
	# erase history from history files
	> profiles/*/dotfiles/.shell_history
}

clean_profiles

set +eu