#!/bin/bash
#-------------------------------------------------------------------------------
# loco_dev_build_release.sh | build a loco release (developer)
#-------------------------------------------------------------------------------

set -eu

function dev_build(){
	local commit_message="${@-}"
	source ./src/code/utils/clean_profiles
	git rm ./dist/loco-dist.zip
	source ./src/code/utils/build_release
	git add ./dist/loco-dist.zip
	git add ./dist/i

	cp ./src/code/utils/install ./dist/i
	git commit -m "${commit_message}"
	git push
}

dev_build "${@-}"

set +eu